name: Deploy to AWS Lambda

on:
  push:
    branches:
      - "**"

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup .NET SDK
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: "8.0.x"

      - name: Install AWS Lambda Tools
        run: dotnet tool install -g Amazon.Lambda.Tools

      - name: Add Lambda Tools to PATH
        run: echo "$HOME/.dotnet/tools" >> $GITHUB_PATH

      - name: Deploy to AWS Lambda
        run: |
          dotnet lambda deploy-function FinbudApi \
            --region us-east-2 \
            --function-handler FinbudApiLambda \
            --function-runtime dotnet8 \
            --function-memory-size 512 \
            --function-timeout 30 \
            --function-url-enable true \
            --configuration Release
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
